# Generated by Django 4.2.1 on 2023-05-20 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='place',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='phone',
            new_name='name',
        ),
    ]
