# Generated by Django 4.2.1 on 2023-05-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_place_info_message_rename_phone_info_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='message',
            field=models.CharField(max_length=150),
        ),
    ]
