# Generated by Django 3.2.18 on 2023-05-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nid',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
