# Generated by Django 3.2.18 on 2023-03-26 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import medicalAnalysis.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('anemia', 'أنيميا'), ('anemia-hada', 'أنيميا حادة ')], default='anemia', max_length=50)),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to=medicalAnalysis.models.image_upload)),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
