# Generated by Django 3.2.18 on 2023-05-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalAnalysis', '0002_auto_20230501_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaltest',
            name='test_type',
            field=models.CharField(choices=[('anemia', 'أنيميا'), ('anemia-hada', 'أنيميا حادة ')], default='anemia', max_length=50),
        ),
    ]
