# Generated by Django 4.2.1 on 2023-05-21 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicalAnalysis', '0004_alter_medicaltest_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaltest',
            name='rate1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicaltest',
            name='rate2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicaltest',
            name='rate3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicaltest',
            name='rate4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicaltest',
            name='rate5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicaltest',
            name='review',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='medicaltest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
