# Generated by Django 4.2.1 on 2023-06-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalAnalysis', '0005_medicaltest_rate1_medicaltest_rate2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaltest',
            name='test_type',
            field=models.CharField(default='anemia', max_length=50),
        ),
    ]
